sudo: true
language: elixir
elixir:
  - 1.4.4
otp_release:
  - 19.3
matrix:
  include:
    - elixir: 1.4.4
      otp_release: 19.3
    - elixir: 1.6.0
      otp_release: 20.0
    - elixir: 1.7.1
      otp_release: 21.0
after_script:
  - mix inch.report
services:
  - rabbitmq
cache:
  directories:
    - _build
    - deps
